---

- name: Create user ssh dir
  become: yes
  become_method: su
  file:
    path: /home/{{ user_name }}/.ssh
    state: directory
    group: '{{ user_name }}'
    owner: '{{ user_name }}'
    mode: 0700

- name: Add ssh key to authorized keys
  become: yes
  become_method: su
  copy:
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    content: "{{ user_pubkey }}"
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0600
